name: WithMyFriends-Core
main: io.ib67.serverutil.WithMyFriends
version: @version@
description: Simple server utility for mini-scale servers.
author: iceBear67
commands:
  wmf:
    description: Main command for WithMyFriends
    aliases: [ tools,tool,util ]